#ifndef CONFIG_H
#define CONFIG_H

#define WS2812_DI_PIN GP29


#define WS2812_DI_PIN GP29
#define RGB_MATRIX_LED_COUNT 36
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 120
#define RGB_MATRIX_SLEEP

#endif // CONFIG_H
