#ifndef CONFIG_H
#define CONFIG_H

// WS2812 RGB Light
#define WS2812_DI_PIN GP29
#define RGBLIGHT_LED_COUNT 36
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8
#define RGBLIGHT_LIMIT_VAL 200
#define RGBLIGHT_SLEEP
#define RGBLIGHT_ANIMATIONS

// Matrix pinout to match arduino_matrix_diag.ino
#define MATRIX_ROWS 5
#define MATRIX_COLS 14
#define MATRIX_ROW_PINS { GP0, GP1, GP2, GP3, GP4 }
#define MATRIX_COL_PINS { GP5, GP6, GP7, GP8, GP9, GP10, GP11, GP12, GP13, GP14, GP15, GP26, GP27, GP28 }
#define DIODE_DIRECTION COL2ROW

#endif // CONFIG_H
