# MCU name
MCU = RP2040

# Bootloader
BOOTLOADER = rp2040
PLATFORM = rp2040
# Build Options
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = yes
RGBLIGHT_ENABLE = no
# RGB_MATRIX_DRIVER = ws2812
# WS2812_DRIVER = vendor
RGB_MATRIX_ENABLE = no
# RGB_MATRIX_KEYPRESSES = yes
ENCODER_ENABLE = no
OLED_ENABLE = no
VIA_ENABLE = yes
