# MCU name
MCU = RP2040

# Bootloader
BOOTLOADER = rp2040
PLATFORM = rp2040
# Build Options
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no
ENCODER_ENABLE = no
OLED_ENABLE = no
VIA_ENABLE = yes

# Keymap
KEYMAP_SECTION_ENABLE = yes
